version: "3"

services:
  php:
    build:
      context: ./opt/php
      dockerfile: Dockerfile
      args:
        PHP_VERSION: "7.3.6-fpm"
    networks:
      app_net:
        ipv4_address: ${PHP_IPADDR}
    volumes:
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./logs/php:/var/log/php
      - ./pro/web:/var/www/html

  nginx:
    build:
      context: ./opt/nginx
      dockerfile: Dockerfile
      args:
        NGINX_VERSION: "1.15.12"
    networks:
      app_net:
        ipv4_address: ${NGINX_IPADDR}
    depends_on:
      - php
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./pro/web:/var/www/html
    ports:
      - ${NGINX_PORTS_START}-${NGINX_PORTS_END}:80-81

  mysql:
    build:
      context: ./opt/mysql
      dockerfile: Dockerfile
      args:
        MYSQL_VERSION: "5.7.26"
    networks:
      app_net:
        ipv4_address: ${MYSQL_IPADDR}
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PWD}"
    volumes:
      - ./data/mysql:/var/lib/mysql

  memcached:
    build:
      context: ./opt/memcached
      dockerfile: Dockerfile
      args:
        MEMCACHED_VERSION: "1.5"
    networks:
      app_net:
        ipv4_address: ${MEMCACHED_IPADDR}

  redis:
    build:
      context: ./opt/redis
      dockerfile: Dockerfile
      args:
        REDIS_VERSION: "5.0.4"
    networks:
      app_net:
        ipv4_address: ${REDIS_IPADDR}
    volumes:
      - ./data/redis:/data/db

  mongo:
    build:
      context: ./opt/mongo
      dockerfile: Dockerfile
      args:
        MONGODB_VERSION: "4.0.9-xenial"
    networks:
      app_net:
        ipv4_address: ${MONGO_IPADDR}
    volumes:
      - ./data/mongo:/data/db

  rabbitmq:
    build:
      context: ./opt/rabbitmq
      dockerfile: Dockerfile
      args:
        RABBITMQ_VERSION: "3.7.17-management"
    networks:
      app_net:
        ipv4_address: ${RABBITMQ_IPADDR}
    environment:
      RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MNG_PORT}:15672"

  pm2:
    build:
      context: ./opt/pm2
      dockerfile: Dockerfile
      args:
        PM2_VERSION: "10-alpine"
    depends_on:
      - mysql
      - rabbitmq
    volumes:
      - ./pro/daemon:/app
      - ./logs/daemon:/tmp

  phpmyadmin:
    build:
      context: ./tools/phpmyadmin
      dockerfile: Dockerfile
      args:
        PMA_VERSION: "4.7"
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_HOST: "mysql"
      PMA_USER: "${PMA_USER}"
      PMA_PASSWORD: "${PMA_PASSWORD}"

volumes:
  document_root:

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
